config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users
  resources :providers
  resources :payments
  resources :scholarships

  resources :clients do
    collection do
      get 'search'
      get 'autocomplete'
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'clients#index' # You can change the root path as needed
end

app/models/scholarship.rb
class Scholarship < ApplicationRecord
  belongs_to :client
  belongs_to :provider
  has_many :payments

  after_save :create_payments

  def child_full_name
    child_first_name + " " + child_last_name
  end

  def display_name
    year.to_s + ", " + child_full_name
  end

  def cycle_ccc_pay
    return cycle_tuition - cycle_discount - cycle_state_voucher - cycle_parent_copay \
    unless cycle_tuition.nil? or cycle_discount.nil? or cycle_state_voucher.nil? or cycle_parent_copay.nil?
    0
  end

  def duration_in_weeks
    (end_date.jd - start_date.jd) / 7
  end

  def n_payments
    payments.count
  end

  def remaining_balance
    Rails.cache.fetch("#{cache_key}/remaining_balance", expires_in: 1.day) do
      balance = 0
      payments.each do |payment|
        balance += payment.remaining_balance(cycle_ccc_pay)
      end
      balance
    end
  end

  after_touch do
    Rails.cache.delete("#{cache_key}/remaining_balance")
  end

  private

  def create_payments
    if billing_cycle == 'Weekly'
      create_weekly_payments
    elsif billing_cycle == 'Monthly'
      create_monthly_payments
    end
  end

  def create_weekly_payments
    current_date = start_date
    while current_date <= end_date
      create_payment_for_week(current_date)
      current_date += 1.week
    end
  end

  def create_monthly_payments
    current_date = start_date
    while current_date <= end_date
      create_payment_for_month(current_date)
      current_date += 1.month
    end
  end

  def create_payment_for_week(date)
    Payment.create!(
      scholarship_id: id,
      client_id: client_id,
      week_end_date: date + 6.days,
      month_name: date.strftime('%B'),
      amount_due: cycle_ccc_pay,
      amount_paid: 0,
      date_paid: nil,
      reference: nil
    )
  end

  def create_payment_for_month(date)
    Payment.create!(
      scholarship_id: id,
      client_id: client_id,
      week_end_date: nil,
      month_name: date.strftime('%B'),
      amount_due: cycle_ccc_pay,
      amount_paid: 0,
      date_paid: nil,
      reference: nil
    )
  end
end

app/controllers/scholarships_controller.rb
class ScholarshipsController < ApplicationController
    before_action :set_scholarship, only: [:show, :edit, :update, :destroy]
  
    def index
      @scholarships = Scholarship.all
    end
  
    def show
    end
  
    def new
      @scholarship = Scholarship.new
    end
  
    def create
      @scholarship = Scholarship.new(scholarship_params)
  
      if @scholarship.save
        redirect_to @scholarship, notice: 'Scholarship was successfully created.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @scholarship.update(scholarship_params)
        redirect_to @scholarship, notice: 'Scholarship was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @scholarship.destroy
      redirect_to scholarships_url, notice: 'Scholarship was successfully destroyed.'
    end
  
    private
  
    def set_scholarship
      @scholarship = Scholarship.find(params[:id])
    end
  
    def scholarship_params
      params.require(:scholarship).permit(
        :year,
        :client_id,
        :child_number,
        :child_first_name,
        :child_last_name,
        :child_ethnicity,
        :child_birth_date,
        :provider_id,
        :billing_cycle,
        :cycle_tuition,
        :cycle_discount,
        :cycle_state_voucher,
        :cycle_parent_copay,
        :start_date,
        :end_date,
        :length
      )
    end
  end
  

app/helpers/scholarships_helper.rb
module ScholarshipsHelper
end

app/views/scholarships/_form.html.erb
<!-- app/views/scholarships/_form.html.erb -->

<%= form_with(model: scholarship, local: true) do |form| %>
  <% if scholarship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scholarship.errors.count, 'error') %> prohibited this scholarship from being saved:</h2>

      <ul>
        <% scholarship.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, value: Time.current.year, required: true %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.collection_select :client_id, Client.all, :id, :first_name, { prompt: 'Select Client' }, required: true %>
  </div>

  <div class="field">
    <%= form.label :child_number %>
    <%= form.number_field :child_number, value: 1, required: true %>
  </div>

  <div class="field">
    <%= form.label :child_first_name %>
    <%= form.text_field :child_first_name, required: true %>
  </div>

  <div class="field">
    <%= form.label :child_last_name %>
    <%= form.text_field :child_last_name, required: true %>
  </div>

  <div class="field">
    <%= form.label :child_ethnicity %>
    <%= form.text_field :child_ethnicity %>
  </div>

  <div class="field">
    <%= form.label :child_birth_date %>
    <%= form.date_field :child_birth_date %>
  </div>

  <div class="field">
    <%= form.label :provider_id %>
    <%= form.collection_select :provider_id, Provider.all, :id, :name, { prompt: 'Select Provider' }, required: true %>
  </div>

  <div class="field">
    <%= form.label :billing_cycle %>
    <%= form.select :billing_cycle, ['Weekly', 'Monthly'], { prompt: 'Select Billing Cycle' }, required: true %>
  </div>

  <div class="field">
    <%= form.label :cycle_tuition %>
    <%= form.number_field :cycle_tuition %>
  </div>

  <div class="field">
    <%= form.label :cycle_discount %>
    <%= form.number_field :cycle_discount %>
  </div>

  <div class="field">
    <%= form.label :cycle_state_voucher %>
    <%= form.number_field :cycle_state_voucher %>
  </div>

  <div class="field">
    <%= form.label :cycle_parent_copay %>
    <%= form.number_field :cycle_parent_copay %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scholarships/_scholarship.html.erb
<div id="<%= dom_id scholarship %>">
</div>

app/views/scholarships/edit.html.erb
<%= render 'shared/header', title: 'Editing Scholarship' %>

<div class="container">
  <h1 class="page-title">Editing Scholarship</h1>

  <%= render "form", scholarship: @scholarship %>

  <br>

  <div>
    <%= link_to "Cancel", @scholarship, class: 'btn btn-secondary' %>
  </div>

</div>

<%= render 'shared/footer' %>

app/views/scholarships/index.html.erb
<%= render 'shared/header', title: 'Scholarships' %>

<div class="container">
  <h1 class="page-title">Scholarships</h1>

  <%= link_to 'New Scholarship', new_scholarship_path, class: 'btn btn-primary btn-sm' %>

  <table class="table table-striped mt-4">
    <thead>
      <tr>
        <th>Year</th>
        <th>Client</th>
        <th>Child Name</th>
        <th>Billing Cycle</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @scholarships.each do |scholarship| %>
        <tr>
          <td><%= scholarship.year %></td>
          <td><%= scholarship.client.full_name %></td>
          <td><%= "#{scholarship.child_first_name} #{scholarship.child_last_name}" %></td>
          <td><%= scholarship.billing_cycle %></td>
          <td>
            <%= link_to 'Show', scholarship, class: 'btn btn-secondary btn-sm' %>
            <%= link_to 'Edit', edit_scholarship_path(scholarship), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Destroy', scholarship, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= render 'shared/footer' %>

app/views/scholarships/new.html.erb
<h1>New scholarship</h1>

<%= render "form", scholarship: @scholarship %>

<br>

<div>
  <%= link_to "Back to scholarships", scholarships_path %>
</div>

app/views/scholarships/show.html.erb
<%= render 'shared/header', title: 'Scholarship Details' %>

<div class="container">
  <h1 class="page-title">Scholarship Details</h1>

  <dl class="row mt-4">
    <%= link_to 'Edit', edit_scholarship_path(@scholarship), class: 'btn btn-warning btn-sm' %>
    <%= link_to 'Scholarships', scholarships_path, class: 'btn btn-secondary btn-sm' %>
  </dd>

  <br><br>

  <dl class="row mt-4">
    <b><dt class="col-sm-3">Year:</b> <%= @scholarship.year %></p>
    <b><dt class="col-sm-3">Client:</b> <%= link_to @scholarship.client.full_name, client_path(@scholarship.client) %></p>
    <b><dt class="col-sm-3">Child Name:</b> <%= @scholarship.child_full_name %></p>
    <b><dt class="col-sm-3">Child Birth Date:</b> <%= @scholarship.child_birth_date %></p>
    <b><dt class="col-sm-3">Provider:</b> <%= link_to @scholarship.provider.name, provider_path(@scholarship.provider) %></p>
    <b><dt class="col-sm-3">Billing Cylce:</b> <%= @scholarship.billing_cycle %></p>
    <b><dt class="col-sm-3">Cycle Tuition:</b> <%= @scholarship.cycle_tuition %></p>
    <b><dt class="col-sm-3">Discount:</b> <%= @scholarship.cycle_discount %></p>
    <b><dt class="col-sm-3">State Voucher:</b> <%= @scholarship.cycle_state_voucher %></p>
    <b><dt class="col-sm-3">Parent Copay:</b> <%= @scholarship.cycle_parent_copay %></p>
    <b><dt class="col-sm-3">CCC Pay:</b> <%= @scholarship.cycle_ccc_pay %></p>
    <b><dt class="col-sm-3">Duration:</b> <%= @scholarship.duration_in_weeks %> weeks</p>
  </dl>

  <br>
  <dt class="col-sm-3"><h2>Payment Schedule</h2></dt>

  <dd class="col-sm-9">
    <table class="table table-bordered mt-3">
      <thead>
        <tr>
          <% if @scholarship.billing_cycle == "Monthly" %>
            <th>Month</th>
          <% else %>
            <th>Week End</th>
          <% end %>
          <th>Total Tuition</th>
          <th>Voucher</th>
          <th>Discount</th>
          <th>Family Co-Pay</th>
          <th>CCC Pay</th>
          <th>Paid</th>
          <th>Credit Used</th>
          <th>Payment Date</th>
          <th>Reference</th>
          <th>Remaining Balance</th>
        </tr>
      </thead>
      <tbody>
        <% @scholarship.payments.each do |payment| %>
          <tr>
            <% if @scholarship.billing_cycle == "Monthly" %>
              <td><%= link_to payment.month_name, edit_payment_path(payment), class: 'nav-link' %></td>
            <% else %>
              <td><%= link_to payment.week_end_date, edit_payment_path(payment), class: 'nav-link' %></td>
            <% end %>
            <td><%= number_to_currency(@scholarship.cycle_tuition) %></td>
            <td><%= number_to_currency(@scholarship.cycle_state_voucher) %></td>
            <td><%= number_to_currency(@scholarship.cycle_discount) %></td>
            <td><%= number_to_currency(@scholarship.cycle_parent_copay) %></td>
            <td><%= number_to_currency(@scholarship.cycle_ccc_pay) %></td>
            <td><%= number_to_currency(payment.amount_paid) %></td>
            <td><%= number_to_currency(0) %></td>
            <td><%= payment.date_paid.try(:strftime, '%Y-%m-%d') %></td>
            <td><%= payment.reference %></td>
            <td><%= number_to_currency(payment.remaining_balance @scholarship.cycle_ccc_pay) %></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td></td>
          <td><strong><%= number_to_currency(@scholarship.cycle_tuition * @scholarship.n_payments) %></strong></td>
          <td><strong><%= number_to_currency(@scholarship.cycle_state_voucher * @scholarship.n_payments) %></strong></td>
          <td><strong><%= number_to_currency(@scholarship.cycle_discount * @scholarship.n_payments) %></strong></td>
          <td><strong><%= number_to_currency(@scholarship.cycle_parent_copay * @scholarship.n_payments) %></strong></td>
          <td><strong><%= number_to_currency(@scholarship.cycle_ccc_pay * @scholarship.n_payments) %></strong></td>
          <td><strong><%= number_to_currency(@scholarship.payments.sum(&:amount_paid)) %></strong></td>
          <td></td>
          <td></td>
          <td></td>
          <td><strong><%= number_to_currency(@scholarship.remaining_balance) %></strong></td>
        </tr>
      </tfoot>
    </table>
  </dd>
</div>

<%= render 'shared/footer' %>