config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users
  resources :providers
  resources :payments
  resources :scholarships

  resources :clients do
    collection do
      get 'search'
      get 'autocomplete'
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'clients#index' # You can change the root path as needed
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :scholarships

    def full_name
        first_name + " " + last_name
    end

    def address_full
        "#{street}, #{city}, #{state} #{zip}"
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_action :set_client, only: [:show, :edit, :update, :destroy]
  
    def index
      @clients = Client.all
    end
  
    def show
    end
  
    def new
      @client = Client.new
    end
  
    def create
      @client = Client.new(client_params)
      if @client.save
        redirect_to clients_path, notice: 'Client was successfully created.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @client.update(client_params)
        redirect_to clients_path, notice: 'Client was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @client.destroy
      redirect_to clients_path, notice: 'Client was successfully destroyed.'
    end

    def search
      first_name = params[:full_name]&.split[0] unless params[:full_name]&.split.count < 1
      last_name = params[:full_name]&.split[1] unless params[:full_name]&.split.count < 2
      @client = Client.find_by(first_name: first_name, last_name: last_name)
      if @client
        redirect_to client_path(@client)
      else
        flash[:alert] = 'Client not found.'
        redirect_to clients_path
      end
    end

    def autocomplete
      first_name = params[:full_name]&.split[0] unless params[:full_name]&.split.count < 1
      last_name = params[:full_name]&.split[1] unless params[:full_name]&.split.count < 2

      clients = Client.where('lower(first_name) LIKE ? AND lower(last_name LIKE ?)', "%#{first_name.downcase}%", "%#{last_name&.downcase}%").limit(5)
  
      render json: clients.map { |client| { id: client.id, full_name: client.full_name } }
    end
  
    private
  
    def set_client
      @client = Client.find(params[:id])
    end
  
    def client_params
      params.require(:client).permit(:first_name, :last_name, :first_enrolled, :street, :city, :state, :zip, :census_tract, :qoz, :date_of_birth, :marital_status, :monthly_salary, :referring_partner, :county_work, :county_residence, :employer, :email, :phone_number, :employer, :job_title, :notes)
    end
  end
  

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
</div>

app/views/clients/_form.html.erb
<%= form_with(model: @client, local: true) do |form| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% @client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :first_enrolled %>
    <%= form.date_field :first_enrolled %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.telephone_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.select :state, ['MD', 'VA', 'DC'], prompt: 'Select State' %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>

  <div class="field">
    <%= form.label :census_tract %>
    <%= form.text_field :census_tract %>
  </div>

  <div class="field">
    <%= form.label :qoz %>
    <%= form.select :qoz, ['Y', 'N'], prompt: 'Select QOZ' %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_field :date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :marital_status %>
    <%= form.select :marital_status, ['Married', 'Divorced', 'Single', 'Separated', 'Widowed', 'Other'], prompt: 'Select Marital Status' %>
  </div>

  <div class="field">
    <%= form.label :monthly_salary %>
    <%= form.text_field :monthly_salary %>
  </div>

  <div class="field">
    <%= form.label :referring_partner %>
    <%= form.text_field :referring_partner %>
  </div>

  <div class="field">
    <%= form.label :county_of_residence %>
    <%= form.text_field :county_of_residence %>
  </div>

  <div class="field">
    <%= form.label :county_work %>
    <%= form.text_field :county_work %>
  </div>

  <div class="field">
    <%= form.label :employer %>
    <%= form.text_field :employer %>
  </div>

  <div class="field">
    <%= form.label :job_title %>
    <%= form.text_field :job_title %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<%= render 'shared/header', title: 'Editing Client' %>

<div class="container">
  <h1 class="page-title">Editing Client</h1>

  <%= render "form", client: @client %>

  <br>

  <div>
    <%= link_to "Cancel", @client, class: 'btn btn-secondary' %>
  </div>

</div>

<%= render 'shared/footer' %>

app/views/clients/index.html.erb
<%= render 'shared/header', title: 'Clients' %>

<div class="container">
  <h1 class="page-title">Clients</h1>

  <!-- Your form -->
  <%= form_tag(search_clients_path, method: :get, class: 'mb-3') do %>
    <div class="input-group">
      <%= text_field_tag :full_name, params[:full_name], class: 'form-control', id: 'client_full_name', placeholder: 'Enter client full name' %>
      <button type="submit" class="btn btn-primary">Search</button>
    </div>
  <% end %>

  <div class="dropdown" id="suggestions-container">
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <!-- Suggestions will be added here dynamically -->
    </div>
  </div>

  <%= link_to 'New Client', new_client_path, class: 'btn btn-primary btn-sm' %>

  <table class="table table-striped mt-4">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Internal ID</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <td><%= client.first_name %></td>
          <td><%= client.last_name %></td>
          <td><%= client.id %></td>
          <td>
            <%= link_to 'Show', client, class: 'btn btn-secondary btn-sm' %>
            <%= link_to 'Edit', edit_client_path(client), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<!-- JavaScript Autocomplete -->
<script>
  document.addEventListener('DOMContentLoaded', function () {
    const fullNameInput = document.getElementById('client_full_name');
    const suggestionsContainer = document.getElementById('suggestions-container');

    fullNameInput.addEventListener('input', function () {
      const fullName = fullNameInput.value.trim();

      // Clear previous suggestions
      suggestionsContainer.querySelector('.dropdown-menu').innerHTML = '';

      // Make an AJAX request to fetch suggestions
      if (fullName.length > 0) {
        fetch(`/clients/autocomplete?full_name=${encodeURIComponent(fullName)}`)
          .then(response => response.json())
          .then(data => {
            const dropdownMenu = suggestionsContainer.querySelector('.dropdown-menu');

            data.forEach(suggestion => {
              const link = document.createElement('a');
              link.href = `/clients/${suggestion.id}`;
              link.classList.add('dropdown-item');
              link.textContent = suggestion.full_name + ", ";
              link.addEventListener('click', function (event) {
                event.preventDefault();
                fullNameInput.value = suggestion.full_name;
                suggestionsContainer.querySelector('.dropdown-menu').innerHTML = ''; // Clear suggestions
              });
              dropdownMenu.appendChild(link);
            });

            // Show the dropdown
            suggestionsContainer.classList.add('show');
          });
      } else {
        // Hide the dropdown if the input is empty
        suggestionsContainer.classList.remove('show');
      }
    });

    // Close the dropdown if clicked outside
    document.addEventListener('click', function (event) {
      if (!suggestionsContainer.contains(event.target)) {
        suggestionsContainer.classList.remove('show');
      }
    });
  });
</script>

<%= render 'shared/footer' %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<%= render 'shared/header', title: 'Client Details' %>

<div class="container">
  <h1 class="page-title"><%= @client.full_name %></h1>

  <%= link_to 'Edit', edit_client_path(@client), class: 'btn btn-warning btn-sm' %>
  <%= link_to 'Create Scholarship', new_scholarship_path, class: 'btn btn-warning btn-sm' %>

  <dl class="row mt-4">
    <b><dt class="col-sm-3">Internal ID:</b> <%= @client.id %></p>
    
    <br>

    <% if !@client.notes.nil? %>
      <dt class="col-sm-3">Notes: <%= @client.notes %></p>
      <br>
    <% end %>

    <b><dt class="col-sm-3">Email:</b> <%= @client.email %></p>
    <b><dt class="col-sm-3">Phone:</b> <%= @client.phone_number %></p>
    <b><dt class="col-sm-3">Address:</b> <%= @client.address_full %></p>
    <b><dt class="col-sm-3">Date of Birth:</b> <%= @client.date_of_birth %></p>
    <b><dt class="col-sm-3">First Enrolled:</b> <%= @client.first_enrolled %></p>
    <b><dt class="col-sm-3">Census Tract:</b> <%= @client.census_tract %></p>
    <b><dt class="col-sm-3">QOZ:</b> <%= @client.qoz %></p>
    <b><dt class="col-sm-3">Marital Status:</b> <%= @client.marital_status %></p>
    <b><dt class="col-sm-3">Monthly Salary:</b> <%= number_to_currency(@client.monthly_salary) %></p>

    <% if !@client.referring_partner.nil? %>
      <b><dt class="col-sm-3">Referring Partner:</b> <%= @client.referring_partner %></p>
    <% end %>

    <b><dt class="col-sm-3">County of Residence:</b> <%= @client.county_residence %></p>
    <b><dt class="col-sm-3">Works in County:</b> <%= @client.county_work %></p>
    <b><dt class="col-sm-3">Employer:</b> <%= @client.employer %></p>
    <b><dt class="col-sm-3">Job Title:</b> <%= @client.job_title %></p>

    <% if @client.scholarships.any? %>
      <br>
      <dt class="col-sm-3"><h2>Payment Schedule</h2></dt>
    <% end %>

    <dd class="col-sm-9">
      <% @client.scholarships.each do |scholarship| %>
        <dt class="col-sm-3"><h3><%= link_to scholarship.display_name, scholarship_path(scholarship), class: 'nav-link' %> </h3></dt>
        <dt class="col-sm-3"><h4>
          Provider: <%= link_to scholarship.provider.name, provider_path(scholarship.provider), class: 'nav-link' %>
        </h4></dt>

        <table class="table table-bordered mt-3">
          <thead>
            <tr>
              <% if scholarship.billing_cycle == "Monthly" %>
                <th>Month</th>
              <% else %>
                <th>Week End</th>
              <% end %>
              <th>Total Tuition</th>
              <th>Voucher</th>
              <th>Discount</th>
              <th>Family Co-Pay</th>
              <th>CCC Pay</th>
              <th>Paid</th>
              <th>Credit Used</th>
              <th>Payment Date</th>
              <th>Reference</th>
              <th>Remaining Balance</th>
            </tr>
          </thead>
          <tbody>
            <% scholarship.payments.each do |payment| %>
              <tr>
                <% if scholarship.billing_cycle == "Monthly" %>
                  <td><%= link_to payment.month_name, edit_payment_path(payment), class: 'nav-link' %></td>
                <% else %>
                  <td><%= link_to payment.week_end_date, edit_payment_path(payment), class: 'nav-link' %></td>
                <% end %>
                <td><%= number_to_currency(scholarship.cycle_tuition) %></td>
                <td><%= number_to_currency(scholarship.cycle_state_voucher) %></td>
                <td><%= number_to_currency(scholarship.cycle_discount) %></td>
                <td><%= number_to_currency(scholarship.cycle_parent_copay) %></td>
                <td><%= number_to_currency(scholarship.cycle_ccc_pay) %></td>
                <td><%= number_to_currency(payment.amount_paid) %></td>
                <td><%= number_to_currency(0) %></td>
                <td><%= payment.date_paid.try(:strftime, '%Y-%m-%d') %></td>
                <td><%= payment.reference %></td>
                <td><%= number_to_currency(payment.remaining_balance scholarship.cycle_ccc_pay) %></td>
              </tr>
            <% end %>
          </tbody>
          <tfoot>
            <tr>
              <td></td>
              <td><strong><%= number_to_currency(scholarship.cycle_tuition * scholarship.n_payments) %></strong></td>
              <td><strong><%= number_to_currency(scholarship.cycle_state_voucher * scholarship.n_payments) %></strong></td>
              <td><strong><%= number_to_currency(scholarship.cycle_discount * scholarship.n_payments) %></strong></td>
              <td><strong><%= number_to_currency(scholarship.cycle_parent_copay * scholarship.n_payments) %></strong></td>
              <td><strong><%= number_to_currency(scholarship.cycle_ccc_pay * scholarship.n_payments) %></strong></td>
              <td><strong><%= number_to_currency(scholarship.payments.sum(&:amount_paid)) %></strong></td>
              <td></td>
              <td></td>
              <td></td>
              <td><strong><%= number_to_currency(scholarship.remaining_balance) %></strong></td>
            </tr>
          </tfoot>
        </table>
      <% end %>
    </dd>

    <!-- Add more attributes as needed... -->
  </dl>
</div>

<%= render 'shared/footer' %>