config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users
  resources :providers
  resources :payments
  resources :scholarships

  resources :clients do
    collection do
      get 'search'
      get 'autocomplete'
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'clients#index' # You can change the root path as needed
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :scholarship

    def remaining_balance(cycle_ccc_pay)
        return cycle_ccc_pay - amount_paid unless cycle_ccc_pay.nil? or amount_paid.nil?
        0
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    before_action :set_payment, only: [:show, :edit, :update, :destroy]
  
    def index
      @payments = Payment.all
    end
  
    def show
    end
  
    def new
      @payment = Payment.new
    end
  
    def create
      @payment = Payment.new(payment_params)
      if @payment.save
        redirect_to payments_path, notice: 'Payment was successfully created.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @payment.update(payment_params)
        redirect_to payments_path, notice: 'Payment was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @payment.destroy
      redirect_to payments_path, notice: 'Payment was successfully destroyed.'
    end
  
    private
  
    def set_payment
      @payment = Payment.find(params[:id])
    end
  
    def payment_params
      params.require(:payment).permit(:scholarship_id, :client_id, :payment_number, :week_end_date, :month_name, :amount_due, :amount_paid, :date_paid, :reference)
    end
  end
  

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= form.label :scholarship_id %>
    <%= form.collection_select :scholarship_id, Scholarship.all, :id, :display_name, { prompt: 'Select Scholarship' }, required: true %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.collection_select :client_id, Client.all, :id, :first_name, { prompt: 'Select Client' }, required: true %>
  </div>

  <div class="field">
    <%= form.label :payment_number %>
    <%= form.number_field :payment_number, value: 1, required: true %>
  </div>

  <div class="field">
    <%= form.label :week_end_date %>
    <%= form.date_field :week_end_date, required: false %>
  </div>

  <div class="field">
    <%= form.label :month_name %>
    <%= form.select :month_name, (1..12).map { |m| [Date::MONTHNAMES[m], m] }, prompt: 'Select Month', required: false %>
  </div>

  <div class="field">
    <%= form.label :amount_due %>
    <%= form.number_field :amount_due, required: true %>
  </div>

  <div class="field">
    <%= form.label :amount_paid %>
    <%= form.number_field :amount_paid %>
  </div>

  <div class="field">
    <%= form.label :date_paid %>
    <%= form.date_field :date_paid %>
  </div>

  <div class="field">
    <%= form.label :reference %>
    <%= form.text_field :referenc %>
  </div>

  <div class="field">
    <%= form.label :cycle_tuition %>
    <%= form.number_field :cycle_tuition %>
  </div>

  <div class="field">
    <%= form.label :cycle_discount %>
    <%= form.number_field :cycle_discount %>
  </div>

  <div class="field">
    <%= form.label :cycle_state_voucher %>
    <%= form.number_field :cycle_state_voucher %>
  </div>

  <div class="field">
    <%= form.label :cycle_parent_copay %>
    <%= form.number_field :cycle_parent_copay %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_form_edit.html.erb
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount_paid %>
    <%= form.number_field :amount_paid %>
  </div>

  <div class="field">
    <%= form.label :date_paid %>
    <%= form.date_field :date_paid %>
  </div>

  <div class="field">
    <%= form.label :reference %>
    <%= form.text_field :reference %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_form_new.html.erb
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= form.label :scholarship_id %>
    <%= form.collection_select :scholarship_id, Scholarship.all, :id, :display_name, { prompt: 'Select Scholarship' }, required: true %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.collection_select :client_id, Client.all, :id, :first_name, { prompt: 'Select Client' }, required: true %>
  </div>

  <div class="field">
    <%= form.label :payment_number %>
    <%= form.number_field :payment_number, value: 1, required: true %>
  </div>

  <div class="field">
    <%= form.label :week_end_date %>
    <%= form.date_field :week_end_date, required: false %>
  </div>

  <div class="field">
    <%= form.label :month_name %>
    <%= form.select :month_name, (1..12).map { |m| [Date::MONTHNAMES[m], m] }, prompt: 'Select Month', required: false %>
  </div>

  <div class="field">
    <%= form.label :amount_due %>
    <%= form.number_field :amount_due, required: true %>
  </div>

  <div class="field">
    <%= form.label :amount_paid %>
    <%= form.number_field :amount_paid %>
  </div>

  <div class="field">
    <%= form.label :date_paid %>
    <%= form.date_field :date_paid %>
  </div>

  <div class="field">
    <%= form.label :reference %>
    <%= form.text_field :referenc %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
</div>

app/views/payments/edit.html.erb
<%= render 'shared/header', title: 'Editing Payment' %>

<div class="container">
  <h1 class="page-title">Editing Payment</h1>

  <%= render "form_edit", payment: @payment %>

  <br>

  <div>
    <%= link_to "Cancel", @payment, class: 'btn btn-secondary' %>
  </div>

</div>

<%= render 'shared/footer' %>

app/views/payments/index.html.erb
<%= render 'shared/header', title: 'Payments' %>

<div class="container">
  <h1 class="page-title">Payments</h1>

  <%= link_to 'New Payment', new_payment_path, class: 'btn btn-primary btn-sm' %>

  <table class="table table-striped mt-4">
    <thead>
      <tr>
        <th>Scholarship</th>
        <th>Client</th>
        <th>Amount Due</th>
        <th>Amount Paid</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @payments.each do |payment| %>
        <tr>
          <td><%= payment.scholarship.display_name %></td>
          <td><%= Client.find(payment.client_id).full_name %></td>
          <td><%= number_to_currency(payment.amount_due) %></td>
          <td><%= number_to_currency(payment.amount_paid) %></td>
          <td>
            <%= link_to 'Show', payment, class: 'btn btn-secondary btn-sm' %>
            <%= link_to 'Edit', edit_payment_path(payment), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<%= render 'shared/footer' %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render "form_new", payment: @payment %>

<br>

<div>
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/show.html.erb
<%= render 'shared/header', title: 'Payment Details' %>


<div class="container">
  <h1 class="page-title">Payment Details</h1>

  <%= link_to 'Edit', edit_payment_path(@payment), class: 'btn btn-warning btn-sm' %>

  <dl class="row mt-4">
    <b><dt class="col-sm-3">Scholarship:</b> <%= link_to @payment.scholarship.display_name, scholarship_path(@payment.scholarship) %></p>
    <b><dt class="col-sm-3">Client:</b> <%= link_to @payment.scholarship.client.full_name, client_path(@payment.scholarship.client) %></p>
    
    <% if @payment.scholarship.billing_cycle == "Weekly" %>
      <b><dt class="col-sm-3">Week End Date:</b> <%= @payment.week_end_date %></p>
    <% else %>
      <b><dt class="col-sm-3">Month:</b> <%= @payment.month_name %></p>
    <% end %>

    <b><dt class="col-sm-3">Amount Due:</b> <%= number_to_currency(@payment.amount_due) %></p>
    <b><dt class="col-sm-3">Amount Paid:</b> <%= number_to_currency(@payment.amount_paid) %></p>

    <% if !@payment.date_paid.nil? %>
      <b><dt class="col-sm-3">Date Paid:</b> <%= @payment.date_paid %></p>
    <% end %>

    <% if !@payment.reference.nil? %>
      <b><dt class="col-sm-3">Reference:</b> <%= @payment.reference %></p>
    <% end %>

  </dl>
</div>

<%= render 'shared/footer' %>